
namespace Device {
    enum Error {
        DEVICE_STARTED = 0,
        STOPPED_BY_SAFETY_BTN,
        STOPPED_RADIATOR_TEMP_TOO_HIGH,
		STOPPED_VOLTAGE_TOO_LOW,
		STOPPED_CURRENT_TOO_HIGH,
		STOPPED_RADIATOR_THERM_CRC,
		STOPPED_RADIATOR_THERM_NOT_AVALIABLE,
		CURRENT_IS_REQUIRED,
		
		NO_ERROR = 0xFF
    };
	
	enum Warning {
		SAFETY_BTN_PRESSED = 1,
		RADIATOR_TEMP_TOO_HIGH,
		VOLTAGE_TOO_LOW,
		CURRENT_TOO_HIGH,
		RECEIVED_NOT_STANDARDIZED_DATA,
		RADIATOR_THERM_CRC,
		BATT_LEFT_THERM_CRC,
		BATT_RIGHT_THERM_CRC,
		WDT_RESET,
		
		NO_WARNING = 0xFF
	};
}